#Adapted from https://github.com/rmohr/docker-activemq.git

FROM openjdk:11-jre-slim

ENV ACTIVE_MQ_VERSION 5.15.9
ENV ACTIVEMQ apache-activemq-$ACTIVE_MQ_VERSION
ENV ACTIVEMQ_TCP=61616 ACTIVEMQ_AMQP=5672 ACTIVEMQ_STOMP=61613 ACTIVEMQ_MQTT=1883 ACTIVEMQ_WS=61614 ACTIVEMQ_UI=8161

ENV ACTIVEMQ_HOME /opt/activemq

COPY conf/* $ACTIVEMQ_HOME-default/conf/

RUN set -x && \
    mkdir -p /opt && \
    apt-get update  && \
    apt-get install -y curl && \
    curl -s -S https://archive.apache.org/dist/activemq/$ACTIVEMQ_VERSION/$ACTIVEMQ-bin.tar.gz | tar xvz -C /opt && \
    ln -s /opt/$ACTIVEMQ $ACTIVEMQ_HOME && \
    cp $ACTIVEMQ_HOME-default/conf/* $ACTIVEMQ_HOME/conf &&\
    groupadd --system activemq && useradd --system -M -g activemq -d $ACTIVEMQ_HOME activemq && \
    chown -R activemq:activemq /opt/$ACTIVEMQ && \
    chown -h activemq:activemq $ACTIVEMQ_HOME && \
    rm -rf /var/cache/apk/*

USER activemq

WORKDIR $ACTIVEMQ_HOME
EXPOSE $ACTIVEMQ_TCP $ACTIVEMQ_AMQP $ACTIVEMQ_STOMP $ACTIVEMQ_MQTT $ACTIVEMQ_WS $ACTIVEMQ_UI

CMD ["/bin/sh", "-c", "bin/activemq console"]