spring:
  profiles:
    active: mongodb-local, activemq

messaging:
  stats-publisher:
    queue-name: VirtualTopic.mu.yanesh.messaging.stats.message
  stats-publisher-clear:
    queue-name: VirtualTopic.mu.yanesh.messaging.stats.clear.message
    
lotto:
  api:
    base-url: http://localhost:9000/api/1.0

server:
  port: 0