spring:
  application:
    name: lotto-api
  profiles:
    active: logger, mongodb-local
    
api:
  version: 1.0

eureka:
  client:
    service-url:
      defaultZone: ${eureka_url:http://localhost:8765/eureka}
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}