spring:
  application:
    name: lotto-api-gateway
  cloud:
    gateway:
      routes:
        id: lotto-api
        url: http://localhost:8761/eureka
        
server:
  port: 0
  
eureka:
  instance:
    instance-id: ${spring.application.name}
