spring:
  application:
    name: lotto-api-gateway
  cloud:
    gateway:
      routes:
        - id: lotto-api
          uri: lb://lotto-api
          predicates:
            - Path=/api/1.0/tirage/**
        - id: lotto-extractor
          uri: lb://lotto-extractor
          predicates:
            - Path=/api/1.0/extractor/**
        
server:
  port: 9000
  
eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
