spring:
  application:
    name: lotto-persister
  profiles:
    active: activemq, mongodb-local

messaging:
  ticket-receiver:
    queue-name: VirtualTopic.mu.yanesh.messaging.ticket.extractor.message

server:
  port: 8100
