spring:
  application:
    name: lotto-persister
  profiles:
    active: activemq, mongodb-local

messaging:
  ticket-receiver:
    queue-name: VirtualTopic.mu.yanesh.messaging.ticket.extractor.message
  stats-receiver:
    queue-name: VirtualTopic.mu.yanesh.messaging.stats.message
  stats-receiver-clear:
    queue-name: VirtualTopic.mu.yanesh.messaging.stats.clear.message

server:
  port: 8100
