spring:
    application:
        name: lottotech-extractor
    profiles:
        active: activemq, logger, mongodb-local
        
api:
    version: 1.0
        
lottotech:
    tirage:
        url: https://loterienationale.mu/en/tirages-et-archives
        param: field_date_du_tirage_value[value][date]
    extractor:
        extract:
            weekends: true
            weekdays: true

messaging:
    ticket-publisher:
        queue-name: VirtualTopic.mu.yanesh.messaging.ticket.extractor.message
    extraction-publisher:
        queue-name: VirtualTopic.mu.yanesh.messaging.extraction.log.extractor.message

extractor:
    scheduler:
        cron: 0 0 * * THU,SUN
        launch-on-startup: true

server:
    port: 8200
