
spring:
  activemq:
    user: rabbitAdminUser
    password: rabbitAdminPwd
    broker-url: failover:(tcp://localhost:61616)?startupMaxReconnectAttempts=5&jms.prefetchPolicy.all=1&jms.redeliveryPolicy.maximumRedeliveries=2
    packages:
      trust-all: true
